basePath: /api/v1
definitions:
  types.Hello:
    properties:
      hello:
        type: string
    type: object
info:
  contact:
    email: russellsimpkins@gmail.com
    name: API Support
  description: Codetest API for Joe.
  license:
    name: MIT
    url: https://github.com/russellsimpkins/simple-api/blob/master/LICENSE
  termsOfService: http://swagger.io/terms
  title: Simple Swagger API.
  version: "1.0"
paths:
  /hello/{who}:
    get:
      parameters:
      - description: Who to say hello to.
        in: path
        name: who
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Hello'
      security:
      - ApiKeyAuth: []
      summary: Executes a simple hello world for demonstration purposes.
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
